Web/Controllers/BaseController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;

namespace Web.Controllers
{
    public class BaseController : Controller
    {
        public int currentUserId;
        public readonly ILogger<HomeController> _logger;

        public BaseController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            if (!int.TryParse(context.HttpContext.User.Claims.FirstOrDefault()?.Value, out currentUserId))
            {
                HttpContext.SignOutAsync().Wait();
                context.Result = RedirectToAction("index", "user");
            }

            base.OnActionExecuting(context);
        }
    }
}

Web/Controllers/LocalizationController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Controllers
{
    public class LocalizationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult SetLanguage(string culture, string returnURL)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName, // name of the cookie
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),  
                new CookieOptions
                {
                    Expires = DateTimeOffset.UtcNow.AddDays(1),
                    IsEssential = true,
                } 
                );
            return Redirect(Request.GetTypedHeaders().Referer.ToString());
        }
    }
}

Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Web.Db;
using Web.Infrastructure;

namespace Web.Controllers
{
    public class UserController : Controller
    {
        protected AppDbContext _dbContext;
        private readonly IStringLocalizer<UserController> _localizer;

        public UserController(AppDbContext dbContext, IStringLocalizer<UserController> localizer)
        {
            _dbContext = dbContext;
            _localizer = localizer;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new Models.User.Login());
        }

        [HttpPost]
        [ModelStateValidationFilter]
        public async Task<IActionResult> Index(Models.User.Login model, string returnUrl = "")
        {
            var hashedPassword = MD5Hash(model.Password);
            var user = _dbContext.User
                 .FirstOrDefault(x =>
                 x.Password == hashedPassword
                 && x.Email == model.Email);

            if (user == null)
            {
                ModelState.AddModelError("mesaj", _localizer["InvalidInformationError"].Value);
            }
            else
            {
                var claims = new List<Claim>() { new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()) };

                var cIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext
                       .SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    new ClaimsPrincipal(cIdentity));

                if (!String.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
                    return Redirect(returnUrl);
                else
                    return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View(new Models.User.Register());
        }

        [HttpPost]
        [ModelStateValidationFilter]
        public IActionResult Register(Models.User.Register model, string returnUrl = "")
        {
            var isValidMail = _dbContext.User.FirstOrDefault(x => x.Email == model.Email.ToLower() || x.Username == model.Username);

            if (isValidMail != null)
            {
                if (isValidMail.Email == model.Email.ToLower())
                    ModelState.AddModelError("", _localizer["ExistingMailAddressError"].Value);

                if (isValidMail.Username == model.Username)
                    ModelState.AddModelError("", _localizer["UsernameAlreadyExists"].Value);
            }
            else
            {
                // db modeli oluştur
                var user = new Db.Entity.User
                {
                    Email = model.Email.ToLower(),
                    Name = model.Name,
                    Password = MD5Hash(model.Password),
                    Username = model.Username
                };

                // context'e modeli ekle
                _dbContext.User.Add(user);

                // db'ye kaydet
                _dbContext.SaveChanges();

                // index'e yolla
                if (!String.IsNullOrEmpty(returnUrl) && Url.IsLocalUrl(returnUrl))
                    return Redirect(returnUrl);
                else
                    return RedirectToAction("Index", "Home");
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("index", "user");
        }

        public string MD5Hash(string input)
        {
            using (var md5 = MD5.Create())
            {
                var result = md5.ComputeHash(Encoding.ASCII.GetBytes(input));
                return Encoding.ASCII.GetString(result);
            }
        }

    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                @*<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("Web")</a>*@
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("Home")</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roadmap" asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("My Roadmaps")</a>
                        </li>
                        <li class="nav-item">
                            <form class="form-inline" asp-area="" asp-controller="User" asp-action="Logout" method="post">
                                <button type="submit" class="nav-link btn btn-link">@SharedLocalizer.GetLocalizedHtmlString("Logout")</button>
                            </form>
                        </li>
                        <li>
                            @await Html.PartialAsync("_SelectLanguagePartial")
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" >
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">@SharedLocalizer.GetLocalizedHtmlString("Privacy")</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Web/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Localization
@using Microsoft.Extensions.Options
@inject IOptions<RequestLocalizationOptions> LocOptions
@{

    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    var cultureItems = LocOptions.Value.SupportedUICultures // all the supported cultures.
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div title="@SharedLocalizer.GetLocalizedHtmlString("Request culture provider:") @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Base" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path"
          method="post" class="form-horizontal" role="form">
        <a style="color:white"> @SharedLocalizer.GetLocalizedHtmlString("Language")</a>
        <a asp-controller="Localization" asp-action="SetLanguage" asp-route-culture="tr-TR"><img src="https://img.icons8.com/emoji/48/000000/turkey-flag-emoji.png" /></a>
        <a asp-controller="Localization" asp-action="SetLanguage" asp-route-culture="en-US"><img src="https://img.icons8.com/emoji/48/000000/united-kingdom-emoji.png" /></a>
    </form>
</div>
@*<script>
    $(document).on("change", "select[name='culture']", function () {
        $("form#selectLanguage").submit();
    });
</script>*@