Web/Models/Roadmap.cs
using FluentValidation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Web.Models.Roadmap
{
    public class Create
    {
        public string Name { get; set; }
        public int Visibility { get; set; } = 1;
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
    }

    public class CreateValidator : AbstractValidator<Create>
    {
        public CreateValidator()
        {

            RuleFor(x => x.Name).NotNull().WithMessage("İsim Zorunlu");
            RuleFor(x => x.Visibility).GreaterThanOrEqualTo(1);
            RuleFor(x => x.EndDate)
                .GreaterThan(x => x.StartDate.Value)
                .WithMessage("Bitiş Tarihi başlangıç tarihinden büyük olmalıdır!")
                .When(x => x.StartDate.HasValue);
        }
    }
    public class Edit
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int Visibility { get; set; } = 1;
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }
    }

    public class EditValidator : AbstractValidator<Edit>
    {
        public EditValidator()
        {
            RuleFor(x => x.Id).NotEmpty().WithMessage("Id zorunlu");
            RuleFor(x => x.Name).NotNull().WithMessage("İsim Zorunlu");
            RuleFor(x => x.Visibility).GreaterThanOrEqualTo(1);
            //RuleFor(x => x.StartDate).NotNull().WithMessage("Geçerli bir tarih girin.");
            RuleFor(x => x.EndDate)
                .GreaterThan(x => x.StartDate.Value)
                .WithMessage("Bitiş Tarihi başlangıç tarihinden büyük olmalıdır!")
                .When(x => x.StartDate.HasValue);
        }
    }

    public class Detail
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public int Visibility { get; set; } = 1;
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }

        public List<RoadmapItem.DetailItem> Items { get; set; }
    }
}

Web/Controllers/RoadmapController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using Web.Db;
using Web.Db.Entity;
using Web.Infrastructure;

namespace Web.Controllers
{
    [Authorize]
    public class RoadmapController : BaseController
    {
        protected AppDbContext _dbContext;
        private readonly IStringLocalizer<RoadmapController> _localizer;

        public RoadmapController(AppDbContext dbContext, IStringLocalizer<RoadmapController> localizer, ILogger<HomeController> logger) : base(logger)
        {
            this._dbContext = dbContext;
            this._localizer = localizer;
        }

        // GET: RoadmapController
        public ActionResult Index()
        {
            List<Roadmap> roadmaps = _dbContext.Roadmap.Where(x => x.UserId == currentUserId && x.Status == (int)StatusEnum.ActiveRoadmap).ToList();
            return View(roadmaps);

        }

        // GET: RoadmapController/Details/5
        public ActionResult Details(Guid id)
        {

            if (Guid.Empty == id)
            {
                ModelState.AddModelError("", _localizer["InvalidId"].Value);
            }
            else
            {
                var roadmapDetail = _dbContext.Roadmap
                    .Include("Items")
                    .FirstOrDefault(x => x.Id == id
                    && x.UserId == currentUserId && x.Status == (int)StatusEnum.ActiveRoadmap);

                if (roadmapDetail != null)
                {
                    var model = new Models.Roadmap.Detail()
                    {
                        Id = roadmapDetail.Id,
                        Name = roadmapDetail.Name,
                        Visibility = roadmapDetail.Visibility,
                        StartDate = roadmapDetail.StartDate,
                        EndDate = roadmapDetail.EndDate,
                        Items = roadmapDetail.Items?
                        .Where(x => x.Status != (int)StatusEnum.DeletedRoadmapItem)
                        .OrderBy(x => x.ParentId).ThenBy(x => x.Order)
                        .Select(x => new Models.RoadmapItem.DetailItem
                        {
                            Id = x.Id,
                            Title = x.Title,
                            Order = x.Order,
                            ParentId = x.ParentId
                        }).ToList()
                    };
                    return View(model);
                }
                else { ModelState.AddModelError("", _localizer["RoadmapNotFoundError"].Value); }
            }

            return View();
        }

        // GET: RoadmapController/Create
        public ActionResult Create()
        {
            return View(new Models.Roadmap.Create());
        }

        // POST: RoadmapController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ModelStateValidationFilter]
        public ActionResult Create(Models.Roadmap.Create model)
        {
            var roadmap = new Roadmap()
            {
                EndDate = model.EndDate,
                Name = model.Name,
                StartDate = model.StartDate,
                Visibility = model.Visibility,
                UserId = currentUserId
            };

            _dbContext.Roadmap.Add(roadmap);

            _dbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: RoadmapController/Edit/5
        public ActionResult Edit(Guid id)
        {

            if (Guid.Empty == id)
            {
                ModelState.AddModelError("", _localizer["InvalidId"].Value);
            }
            else
            {
                var fromdb = _dbContext.Roadmap.FirstOrDefault(x => x.Id == id && x.UserId == currentUserId && x.Status == (int)StatusEnum.ActiveRoadmap);
                if (fromdb != null)
                {
                    var model = new Models.Roadmap.Edit()
                    {
                        Id = fromdb.Id,
                        EndDate = fromdb.EndDate,
                        Name = fromdb.Name,
                        StartDate = fromdb.StartDate,
                        Visibility = fromdb.Visibility
                    };
                    return View(model);
                }
                else { ModelState.AddModelError("", _localizer["RoadmapNotFoundError"].Value); }
            }

            return View();
        }

        // POST: RoadmapController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ModelStateValidationFilter]
        public ActionResult Edit(Models.Roadmap.Edit model)
        {
            var fromdb = _dbContext.Roadmap.FirstOrDefault(x => x.Id == model.Id && x.UserId == currentUserId && x.Status == (int)StatusEnum.ActiveRoadmap);
            if (fromdb != null)
            {

                fromdb.Name = model.Name;
                fromdb.StartDate = model.StartDate;
                fromdb.EndDate = model.EndDate;
                fromdb.Visibility = model.Visibility;

                _dbContext.Roadmap.Update(fromdb);
                _dbContext.SaveChanges();

                return RedirectToAction("Index", "Roadmap");
            }
            else { ModelState.AddModelError("", _localizer["RoadmapNotFoundError"].Value); }

            return View(model);
        }

        // GET: RoadmapController/Delete/5
        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            if (id == Guid.Empty) return NotFound();

            var roadmapToBeDeleted = _dbContext.Roadmap.FirstOrDefault(x => x.Id == id && x.UserId == currentUserId && x.Status == (int)StatusEnum.ActiveRoadmap);
            if (roadmapToBeDeleted != null) return View(roadmapToBeDeleted);

            ModelState.AddModelError("", _localizer["RoadmapNotFoundError"].Value);

            return RedirectToAction(nameof(Index));
        }

        // POST: RoadmapController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            var roadmapToBeDeleted = _dbContext.Roadmap.FirstOrDefault(x => x.Id == id && x.UserId == currentUserId && x.Status == (int)StatusEnum.ActiveRoadmap);

            if (roadmapToBeDeleted != null)
            {
                roadmapToBeDeleted.Status = (int)StatusEnum.DeletedRoadmap;
                _dbContext.Roadmap.Update(roadmapToBeDeleted);
                _dbContext.SaveChanges();
            }
            else { ModelState.AddModelError("", _localizer["RoadmapNotFoundError"].Value); }

            return RedirectToAction(nameof(Index));
        }
    }
}

Web/Controllers/RoadmapItemController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using Web.Db;
using Web.Db.Entity;
using Web.Infrastructure;
using Web.Models.RoadmapItem;

namespace Web.Controllers
{
    public class RoadmapItemController : BaseController
    {
        protected AppDbContext _dbContext;
        private readonly IStringLocalizer<RoadmapItemController> _localizer;

        public RoadmapItemController(AppDbContext dbContext, ILogger<HomeController> logger, IStringLocalizer<RoadmapItemController> localizer) : base(logger)
        {
            _dbContext = dbContext;
            _localizer = localizer;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create(Guid RoadmapId, int? Order, Guid? ParentId)
        {
            var model = new Create { Order = Order, RoadmapId = RoadmapId, ParentId = ParentId };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ModelStateValidationFilter]
        public IActionResult Create(Create model)
        {
            var item = new RoadmapItem()
            {
                Title = model.Title,
                RoadmapId = model.RoadmapId,
                ParentId = model.ParentId
            };

            // Belli sıraya ekler, eklenen sıradali ve sonraki kayıtları bir alt sıraya taşır.
            if (model.Order.HasValue && model.Order.Value > 0)
            {
                item.Order = model.Order.Value;

                var afterItems = _dbContext.RoadmapItem
                    .Where(x => x.RoadmapId == model.RoadmapId
                    && x.ParentId == model.ParentId
                    && x.Status != (int)StatusEnum.DeletedRoadmapItem
                    && (x.Order == item.Order || x.Order > item.Order))
                    .OrderBy(x => x.Order)
                    .ToList();

                if (afterItems != null && afterItems.Count > 0)
                {
                    foreach (var after in afterItems)
                    {
                        after.Order += 1;
                        _dbContext.RoadmapItem.Update(after);
                    }
                }
            }

            // En son sıraya ekler
            else
            {
                var parent = _dbContext.RoadmapItem
                .Where(x => x.RoadmapId == model.RoadmapId
                && x.Status != (int)StatusEnum.DeletedRoadmapItem
                && x.ParentId == model.ParentId)
                .OrderByDescending(x => x.Order)
                .FirstOrDefault();

                if (parent != null) item.Order = parent.Order + 1;
            }

            _dbContext.RoadmapItem.Add(item);
            _dbContext.SaveChanges();
            return RedirectToAction("Details", "Roadmap", new { id = model.RoadmapId });
        }

        public IActionResult Delete(Guid RoadmapId, Guid ItemId)
        {
            var toDelete = _dbContext.RoadmapItem
                .FirstOrDefault(x => x.RoadmapId == RoadmapId
                && x.Id == ItemId
                && x.Status != (int)StatusEnum.DeletedRoadmapItem);

            if (toDelete != null)
            {
                // kaydı silinecek olarak işaretle.
                toDelete.Status = (int)StatusEnum.DeletedRoadmapItem;
                _dbContext.RoadmapItem.Update(toDelete);

                // silinecek kayda ait alt kayıtlar varsa onları da sil.
                var children = _dbContext.RoadmapItem
                    .Where(x => x.RoadmapId == RoadmapId
                    && x.Status != (int)StatusEnum.DeletedRoadmapItem
                    && x.ParentId == toDelete.Id
                    ).ToList();

                if (children != null && children.Count > 0)
                {
                    foreach (var child in children) { child.Status = (int)StatusEnum.DeletedRoadmapItem; }
                    _dbContext.RoadmapItem.UpdateRange(children);
                }

                // Kendinden sonraki kayıtların sırasını azalt.
                var afterItems = _dbContext.RoadmapItem
                   .Where(x => x.RoadmapId == RoadmapId
                   && x.ParentId == toDelete.ParentId
                   && x.Status != (int)StatusEnum.DeletedRoadmapItem
                   && x.Id != toDelete.Id
                   && x.Order > toDelete.Order)
                   .OrderBy(x => x.Order)
                   .ToList();

                if (afterItems != null && afterItems.Count > 0)
                {
                    foreach (var after in afterItems) { after.Order--; }
                    _dbContext.RoadmapItem.UpdateRange(afterItems);
                }

                // db'yi güncelle
                _dbContext.SaveChanges();
            }
            else { ModelState.AddModelError("", _localizer["RoadmapItemNotFoundError"]); }

            return RedirectToAction(nameof(RoadmapController.Details), "Roadmap", new { id = RoadmapId });
        }
    }
}

Web/Views/Roadmap/Create.cshtml
@model Web.Models.Roadmap.Create

@{
    ViewData["Title"] = @SharedLocalizer.GetLocalizedHtmlString("Roadmap Create");
}

<h1>@SharedLocalizer.GetLocalizedHtmlString("Roadmap Create")</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label">@SharedLocalizer.GetLocalizedHtmlString("Name")</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Visibility" class="control-label">@SharedLocalizer.GetLocalizedHtmlString("Visibility")</label>
                <input asp-for="Visibility" class="form-control" />
                <span asp-validation-for="Visibility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label">@SharedLocalizer.GetLocalizedHtmlString("StartDate")</label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label">@SharedLocalizer.GetLocalizedHtmlString("EndDate")</label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value=@SharedLocalizer.GetLocalizedHtmlString("Create") class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("Back to list")</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Views/Roadmap/Delete.cshtml
@model Web.Db.Entity.Roadmap

@{
    ViewData["Title"] = @SharedLocalizer.GetLocalizedHtmlString("Delete");
}

<h1>@SharedLocalizer.GetLocalizedHtmlString("Delete")</h1>

<h3>@SharedLocalizer.GetLocalizedHtmlString("Are you sure you want to delete this?")</h3>
<div>
    <h4>@SharedLocalizer.GetLocalizedHtmlString("Roadmap")</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @SharedLocalizer.GetLocalizedHtmlString("Id")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer.GetLocalizedHtmlString("Name")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer.GetLocalizedHtmlString("Visibility")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Visibility)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer.GetLocalizedHtmlString("Status")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer.GetLocalizedHtmlString("StartDate")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer.GetLocalizedHtmlString("EndDate")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer.GetLocalizedHtmlString("UserId")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
    </dl>

    <form asp-action="DeleteConfirmed">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value=@SharedLocalizer.GetLocalizedHtmlString("Delete") class="btn btn-danger" /> |
        <a asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("Back to list")</a>
    </form>
</div>

Web/Views/Roadmap/Details.cshtml
@model Web.Models.Roadmap.Detail

@{
    ViewData["Title"] = @SharedLocalizer.GetLocalizedHtmlString("Details");
}

<h1>@SharedLocalizer.GetLocalizedHtmlString("Details")</h1>

<div>
    <h4>@SharedLocalizer.GetLocalizedHtmlString("Roadmap")</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @SharedLocalizer.GetLocalizedHtmlString("Name")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer.GetLocalizedHtmlString("Visibility")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Visibility)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer.GetLocalizedHtmlString("StartDate")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @SharedLocalizer.GetLocalizedHtmlString("EndDate")
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">@SharedLocalizer.GetLocalizedHtmlString("Edit")</a> |
    <a asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("Back to list")</a>
</div>

@Html.ActionLink("Item Ekle", "Create", "RoadmapItem", new { RoadmapId = Model.Id })
@if (Model.Items != null && Model.Items.Count > 0)
{
    <table class="table table-striped table-hover table-borderless">
        <caption>Toplam @Model.Items.Count(x => !x.ParentId.HasValue) Kayıt</caption>
        <thead>
            <tr>
                <th scope="col">Order</th>
                <th scope="col">Title</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Items.Where(x => !x.ParentId.HasValue))
            {
                var childCount = Model.Items.Count(x => x.ParentId == item.Id);


                <tr>
                    <td>@item.Order</td>
                    <td>@item.Title</td>
                    <td style="text-align:right;">
                        @Html.ActionLink("Sil", "Delete", "RoadmapItem", new { RoadmapId = Model.Id, ItemId = item.Id })
                        |
                        @Html.ActionLink("Alt Kayıt Ekle", "Create", "RoadmapItem", new { RoadmapId = Model.Id, ParentId = item.Id })
                    </td>
                </tr>
                @if (childCount > 0)
                {
                    <tr>
                        <td colspan="4">
                            <table class="table table-sm">
                                <caption>Toplam @childCount Kayıt</caption>
                                <tbody>
                                    @foreach (var child in Model.Items.Where(x => x.ParentId == item.Id))
                                    {
                                        <tr>
                                            <td></td>
                                            <td>@child.Order</td>
                                            <td>@child.Title</td>
                                            <td style="text-align:right;">
                                                @Html.ActionLink("Sil", "Delete", "RoadmapItem", new { RoadmapId = Model.Id, ItemId = child.Id })
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </td>
                    </tr>
                }

            }
        </tbody>
    </table>
}

Web/Views/Roadmap/Edit.cshtml
@model Web.Models.Roadmap.Edit

@{
    ViewData["Title"] = @SharedLocalizer.GetLocalizedHtmlString("Edit");
}


<h4>@SharedLocalizer.GetLocalizedHtmlString("Edit")</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="Id" type="hidden" />
            <div class="form-group">
                <label asp-for="Name" class="control-label">@SharedLocalizer.GetLocalizedHtmlString("Name")</label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Visibility" class="control-label">@SharedLocalizer.GetLocalizedHtmlString("Visibility")</label>
                <input asp-for="Visibility" class="form-control" />
                <span asp-validation-for="Visibility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label">@SharedLocalizer.GetLocalizedHtmlString("StartDate")</label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label">@SharedLocalizer.GetLocalizedHtmlString("EndDate")</label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value=@SharedLocalizer.GetLocalizedHtmlString("Create") class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@SharedLocalizer.GetLocalizedHtmlString("Back to list")</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Views/Roadmap/Index.cshtml
@model IEnumerable<Web.Db.Entity.Roadmap>
@{
    ViewData["Title"] = @SharedLocalizer.GetLocalizedHtmlString("Roadmaps");
}

<h1>@ViewData["Roadmaps"]</h1>
<p>
   <a asp-action="Create">@SharedLocalizer.GetLocalizedHtmlString("Create New")</a>
</p>
<div class="row">
    <div class="col-md-12">
        <table class="table">
            <thead class="table-info">
                <tr>
                    <th>@Html.DisplayNameFor(model => model.Id)</th>
                    <th>@SharedLocalizer.GetLocalizedHtmlString("Name")</th>
                    <th>@SharedLocalizer.GetLocalizedHtmlString("Visibility")</th>
                    <th>@SharedLocalizer.GetLocalizedHtmlString("Status")</th>
                    <th>@SharedLocalizer.GetLocalizedHtmlString("StartDate")</th>
                    <th>@SharedLocalizer.GetLocalizedHtmlString("EndDate")</th>
                    <th>@SharedLocalizer.GetLocalizedHtmlString("UserId")</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Visibility)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Status)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.StartDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.EndDate)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.UserId)
                        </td>
                        <td>
                            @Html.ActionLink(@SharedLocalizer.GetLocalizedHtmlString("Edit"), "Edit", new { id = item.Id })
                            @Html.ActionLink(@SharedLocalizer.GetLocalizedHtmlString("Details"), "Details", new { id = item.Id })
                            @Html.ActionLink(@SharedLocalizer.GetLocalizedHtmlString("Delete"), "Delete", new { id = item.Id })
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>